import type { NativeModule, EmitterSubscription } from 'react-native';
import type { Float, Int32 } from 'react-native/Libraries/Types/CodegenTypes';

export enum PicthDetectorErrors {
  BASE,
  LINKING_ERROR,
  PERMISSIONS_ERROR,
  UNAVAILABLE_ERROR,
}

/**
 * Event emitter subscription
 */
export type Subscription = EmitterSubscription | undefined;

/**
 * Available musical tones.
 * @see `https://en.wikipedia.org/wiki/Musical_tone`
 */
export type Tone =
  | 'C'
  | 'C#'
  | 'D'
  | 'D#'
  | 'E'
  | 'F'
  | 'F#'
  | 'G'
  | 'G#'
  | 'A'
  | 'A#'
  | 'B';

/**
 * Result generated by pitch estimation process.
 */
export type Data = {
  /**
   * Pitch frequency in hertz.
   */
  frequency: Float;
  tone: Tone;
};

/**
 * A callback function called by event emitted from native side.
 */
export type Callback = (data: Data) => void;

/**
 * Available pitch estimation algorithm.
 * @see `https://0110.be/releases/TarsosDSP/TarsosDSP-latest/TarsosDSP-latest-Documentation/`
 */
export type PitchEstimationAlgorithm =
  | 'AMDF'
  | 'DYNAMIC_WAVELET'
  | 'FFT_PITCH'
  | 'FFT_YIN'
  | 'MPM'
  | 'YIN';

/**
 * Pitch detector configuration.
 */
export type PicthDetectorConfig = {
  algorithm?: PitchEstimationAlgorithm;
  bufferOverLap?: Int32;
  bufferSize?: Int32;
  sampleRate?: Float;
};

/**
 * PitchDetector native module interface
 */
export interface NativeModuleImplementation extends NativeModule {
  /**
   * Start audio recording and pitch detection with provided configs
   * @param config
   * @default
   * ```ts
   * {
   *  algorithm: 'YIN',
   *  bufferOverLap: 0,
   *  bufferSize: 1024,
   *  sampleRate: 22050,
   * }
   * ```
   * @returns Promise<void>
   */
  start: (config: PicthDetectorConfig) => Promise<void>;

  /**
   * Stop audio recording and pitch detection
   * @returns Promise<void>
   */
  stop: () => Promise<void>;

  /**
   * Get current status
   * @returns Promise<boolean>
   */
  isRecording: () => Promise<void>;
}
