name: Generate Documentation

on:
  push:
    branches: [main, master]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js Version 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.x

      - name: Test Build
        run: |
          cd website/
          npm i
          npm run build

  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: 'Use Node.js Version 16.x'
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.x

      - name: Add key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT

      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USERNAME }}
          cd website/
          npm i
          npm run build
          npx docusaurus deploy